### ISSUE TITLE
Error when attempting to grab an object from server using evalServer().

### ISSUE THREAD

**Issue by psalveson** [SciViews/svSocket#3]
This issue seems to be specific to running the svSocket server as as a "job" within Rstudio. Running the server via Rscript (CLI) or another instance of Rstudio works fine.

I receive the following error when I attempt to grab an object from the socket server (running as a "job" within Rstudio):
```
> evalServer(con2, stream_tbl) 
[1] "Error in eval(parse(text = \"stream_tbl\")) : object 'stream_tbl' not found\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in eval(parse(text = "stream_tbl")): object 'stream_tbl' not found>
```
I incorporated some ls() checks into my server script, and the stream_tbl object is definitely present in the environment. As mentioned above, everything works fine if I execute the server script using Rscript (CLI) or open up another instance of Rstudio and execute the script. Is there a obvious solution to this? I can post an MWE if needed.

Peter

**Comment by phgrosjean** [comment]
Late answer, but I cannot reproduce this. Starting a socket server in a RStudio job seems to work well for me, including to retrieve objects from that server. I use R 4.0.0, svSocket 1.0.0, and RStudio 1.2.5042 on MacOS 10.15.4 Catalina for the test.

**Comment by phgrosjean** [comment]
Closed because not reproducible. In case this problem resurfaces on your side, please, open a new issue.
