### ISSUE TITLE
Allow using incomplete lines

### ISSUE THREAD

**Issue by ManuelHentschel** [SciViews/svSocket#4]
In [vscDebugger/websocket ](https://github.com/ManuelHentschel/vscDebugger/tree/websocket) (more specifically [here](https://github.com/ManuelHentschel/vscDebugger/blob/websocket/R/websocket.R#L14:L17)) I am trying to use this package to handle requests sent by a debug client and send back responses via a tcp socket.

As far as I understand, the functions from this package handle messages only line by line. Unfortunately, the messages specified in the [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/overview#base-protocol) are not terminated with line breaks, so this approach did not work out of the box.

I tried to modify svSocket [here](https://github.com/SciViews/svSocket/compare/master...ManuelHentschel:readchars) to also read incomplete messages and it seems to work, but I don't know enough about tcl to know if these changes are a good way to achieve this.

Is reading/writing incomplete lines a feature you would consider implementing?

**Comment by phgrosjean** [comment]
I surely understand there could be uses for {svSocket} with incomplete lines. However, the way the tcl socket library works does not allow it in its text line mode that I use. It would be necessary to reengineer a big part of the core of svSocket to implement this feature.

There is still a problem: how do you detect a message is complete? With sockets, message streams can be send piece by piece, and you need a way to detect this is the end of a message (currently, it is the end of line character that plays this role). In you test with the debugger, you probably did not encountered a message long enough to be passed by chunks, but in a more general context. So, what mechanisms should you use to detect that you got the complete message?

I close this issue, and I am sorry I could not do that for you. However, if you find a workable solution on your side, I would be happy to review a pull request to enhance {svSocket} and allow it to work the way you would like.

Best,

Philippe Grosjean

**Comment by ManuelHentschel** [comment]
Thanks for the detailed response, makes sense that you don't want to reengineer the entire package for this!

Regarding the detection of complete messages: DAP-messages specify their length at the beginning, so you can just cache chunks until you reach this length. E.g.
```
Content-Length: 119\r\n
\r\n
{
    "seq": 153,
    "type": "request",
    "command": "next",
    "arguments": {
        "threadId": 3
    }
}
```
(without `\r\n` at the end)

I have no experience with tcl whatsoever, so I'll probably look into some C/C++ solution for this.

Best,
Manuel
