### ISSUE TITLE
SystemRequirements is missing in DESCRIPTION

### ISSUE THREAD

**Issue by hubutui** [SciViews/svSocket#5]
Hello, it needs a working version of Tcl/Tk (>= 8.4), but `SystemRequirements` field is missing in `DESCRIPTION`.

**Comment by phgrosjean** [comment]
Yes and no. You are right, Tcl/Tk is required technically. However, {tcltk2} depends on {tcltk} (one of the base packages) that is in charge of the main R <-> Tcl/Tk interaction. In base R, developers decided to rely on another mechanism to inform of dependencies, that is, `capabilities("tcltk")` and to possibly provide a version of Tcl/Tk with R (e.g., on Windows). The various platform-specific R FAQs that explain how to install Tcl/Tk and compile R to support Tcl/Tk.
Once the {tcltk} R base package is working, there is no additional system dependencies for {tcltk2}, that is, it is developed in a way that it brings together all the Tcl and Tk additional libraries without needing to install them separately. I don't want to misinform the potential user of {tcltk2} by giving him the impression something more has to be system installed. That is why `SystemRequirements` is not indicated (or if you prefer, is empty).
